services:
  tts:
    image: ghcr.io/coqui-ai/xtts-streaming-server:latest-cuda121
    ports:
      - "8000:80"
    environment:
      - COQUI_TOS_AGREED=1
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
